### ISSUE TITLE
Would it be possible to modify it to do this?

### ISSUE THREAD

**Issue by lserlu** [thversfelt/AutoHit#2]
There is this hit that is almost the same as the one this script works for, but only with "good" and "bad" buttons. Would there be any way to modify it to make it work for that?
pic: https://i.imgur.com/cJVbZdH.png
I've tried to, but I stopped programing long time ago and damn I'm rusty.

**Comment by thversfelt** [comment]
It is difficult for me to create a version of AutoHit for a HitApp that I don't have access to. However, I might be able to create it if the following things hold:

1. For every hit, the "good" and "bad" buttons are always at the same screen coordinates.
2. The submit button also always has the same screen coordinates.

If you can figure out if those two things hold, I could create a seperate version that will work with your HitApp.

**Comment by lserlu** [comment]
> 
> 
> It is difficult for me to create a version of AutoHit for a HitApp that I don't have access to. However, I might be able to create it if the following things hold:
> 
>     1. For every hit, the "good" and "bad" buttons are always at the same screen coordinates.
> 
>     2. The submit button also always has the same screen coordinates.
> 
> 
> If you can figure out if those two things hold, I could create a seperate version that will work with your HitApp.

Hello! I managed to do it. I'll post it in case it may be useful to you in the future.
I saw that changes to the css doesn't revert when you click a button. However, it changes between 2 css, meaning on the 1st hit you get css A, on the 2nd css B, on the 3rd css A etc.
So you edit both buttons' css and make the height of them very high. Then I used tinytask to click them, since even if they moved they'd be clickable.
Thanks for replying!

**Comment by thversfelt** [comment]
I am glad to hear you managed to do it by yourself! And that sounds like a good solution.
